version: "3.7"
services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./static:/app/static
      - ./packages/db/prisma/dev.db:/app/packages/db/prisma/dev.db
    ports:
      - "7777:7777"
      - "3000:3000"